import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import "./globals.css";

const font = Poppins({
  subsets: ["latin"],
  weight: '400'
});

export const metadata: Metadata = {
  title: "AVK Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}

        className={font.className}
      >
        {children}
      </body>
    </html>
  );
}
